/* eslint-disable */

/* tslint:disable */

/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { FieldToSend, Model, Score } from './apps/list-template-configurator/list-template-configurator.interface';
import { IModal } from './libs/modal';
import { StyleEventDetail } from './shared/scx-radio-group/scx-radio-button/scx-radio-button';
import { RadioGroupChangeEventDetail } from './shared/scx-radio-group/scx-radio-group';

export { IModal } from './libs/modal';
export { FieldToSend, Model, Score } from './apps/list-template-configurator/list-template-configurator.interface';
export { StyleEventDetail } from './shared/scx-radio-group/scx-radio-button/scx-radio-button';
export { RadioGroupChangeEventDetail } from './shared/scx-radio-group/scx-radio-group';
export namespace Components {
  interface ListTemplateConfigurator {
    modal: IModal;
  }
  interface ScxAddModel {
    saveCurrentStep: () => Promise<'model' | 'mapping' | null>;
    saveMappings: () => Promise<boolean>;
    saveModel: () => Promise<boolean>;
  }
  interface ScxAddScore {
    addNewField?: boolean;
    /**
     * @default { ...this.initField }
     */
    field: FieldToSend;
    /**
     * @default 0
     */
    fieldIndex: number;
    scope: 'Contactability' | 'Propensity';
  }
  interface ScxEmptyState {
    esTitle?: string;
    icon: string;
    label?: string;
  }
  /**
   * Example Components Showcase
   * Dynamic tab-based documentation component using Shoelace tabs.
   * Features:
   * - Shoelace sl-tab-group for native tab UI
   * - Easy to add new components (just add to tabs array)
   * - Live interactive examples
   * - Code snippets with syntax highlighting
   * - API documentation tables
   * Adding a new component:
   * 1. Add new object to `tabs` array in componentWillLoad()
   * 2. Create render method for content
   * 3. Done! Tab is automatically rendered
   * Usage:
   * ```html
   * <scx-example-components></scx-example-components>
   * ```
   */
  interface ScxExampleComponents {}
  /**
   * Range Example Component
   * Demonstrates various use cases of the Shoelace sl-range component with different configurations.
   * Features:
   * - Basic range slider with default settings
   * - Custom min, max, and step values
   * - Range with labels and help text
   * - Range with tooltip for real-time value display
   * - Disabled state demonstration
   * - Multiple ranges with different configurations
   * - Real-time value updates
   * Usage:
   * ```html
   * <scx-example-range></scx-example-range>
   * ```
   * sl-range Documentation:
   * https://shoelace.style/components/range
   */
  interface ScxExampleRange {}
  interface ScxFileUploader {
    esTitle?: string;
    icon: string;
    label?: string;
  }
  interface ScxIconsExample {}
  interface ScxMappingTable {
    saveMappings: () => Promise<boolean>;
  }
  /**
   * Example Modal Component
   * Demonstrates how to create a modal content component that works with the Modal Service.
   * Key Patterns:
   * - Receives `modal` prop from Modal Service
   * - Calls `modal.close()` with appropriate data
   * - Uses confirm/dismiss flags to indicate user action
   * - Follows standard modal structure with modal-wrapper, modal-head, modal-content, modal-footer
   * Usage:
   * ```typescript
   * import { starter } from '../../di/containers';
   * const modal = starter.modal;
   * modal.create({
   *   component: 'scx-example-modal',
   *   width: '500px',
   *   dismissOnEsc: true,
   *   backdropDismiss: true,
   *   componentProps: {
   *     modalTitle: 'Confirm Action',
   *     message: 'Are you sure you want to proceed?'
   *   }
   * });
   * modal.onDismiss((data) => {
   *   if (data.confirm) {
   *     console.log('User confirmed');
   *   } else {
   *     console.log('User cancelled');
   *   }
   * });
   * modal.show();
   * ```
   */
  interface ScxModalExample {
    /**
     * Modal message (optional) Passed via componentProps
     * @default 'This is an example modal component.'
     */
    message: string;
    /**
     * Modal service reference Automatically injected by Modal Service
     */
    modal: IModal;
    /**
     * Modal title (optional) Passed via componentProps
     * @default 'Example Modal'
     */
    modalTitle: string;
  }
  interface ScxRadioButton {
    /**
     * If `true`, the radio is selected.
     * @default false
     */
    checked: boolean;
    /**
     * If `true`, the user cannot interact with the radio.
     * @default false
     */
    disabled: boolean;
    /**
     * The name of the control, which is submitted with the form data.
     * @default this.inputId
     */
    name: string;
    /**
     * The size of the radio button.
     * @default 'medium'
     */
    size: 'small' | 'medium' | 'large';
    /**
     * The value of the radio button.
     */
    value?: unknown;
    /**
     * The color variant of the radio button.
     * @default 'default'
     */
    variant: 'default' | 'neutral' | 'light';
  }
  interface ScxRadioGroup {
    /**
     * If `true`, the radios can be deselected.
     * @default false
     */
    allowEmptySelection: boolean;
    /**
     * The size variant of the radio group. With hug each button accords its size to its content.
     * @default 'fill'
     */
    contain: 'fill' | 'hug';
    /**
     * The name of the control, which is submitted with the form data.
     * @default this.inputId
     */
    name: string;
    /**
     * The size of the radio buttons.
     * @default 'medium'
     */
    size: 'small' | 'medium' | 'large';
    /**
     * The value of the radio group.
     */
    value?: unknown | null;
    /**
     * The color variant of the radio group.
     * @default 'default'
     */
    variant: 'default' | 'neutral' | 'light';
  }
  interface ScxRoot {
    /**
     * @default ''
     */
    apiUrl: string;
  }
  interface ScxScoreField {
    editMode: boolean;
    field: FieldToSend;
    nScore: number;
    /**
     * @default []
     */
    otherScore: Score[];
    switch?: 1 | 3 | null;
  }
  interface ScxScorePanel {
    scope: 'Contactability' | 'Propensity';
  }
  /**
   * Tabulator Example Component
   * Demonstrates how to use Tabulator with custom styling and sorting.
   * Features:
   * - Custom theme using tabulator-theme mixin
   * - Sortable columns (click headers)
   * - Movable rows (drag and drop)
   * - Sample data with multiple types
   * - Responsive layout
   * - Pagination
   * Usage:
   * ```html
   * <scx-tabulator-example></scx-tabulator-example>
   * ```
   */
  interface ScxTabulatorExample {}
  /**
   * Outbound Manager Application Component
   * Demonstrates core patterns for SmileCX applications:
   * - Service access via container getter (NOT
   * @Prop injection)
   * - Reactive state with BehaviorSubject subscriptions
   * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
   * - Event handlers for user interactions
   * - i18n with tt() function
   * This component is the reference implementation for external developers
   * building their own SmileCX-compatible applications.
   * Pattern: Application layer (business logic + UI)
   */
  interface SmilecxOutboundManager {}
}
export interface ScxAddScoreCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLScxAddScoreElement;
}
export interface ScxFileUploaderCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLScxFileUploaderElement;
}
export interface ScxMappingTableCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLScxMappingTableElement;
}
export interface ScxRadioButtonCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLScxRadioButtonElement;
}
export interface ScxRadioGroupCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLScxRadioGroupElement;
}
export interface ScxScoreFieldCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLScxScoreFieldElement;
}
declare global {
  interface HTMLListTemplateConfiguratorElement extends Components.ListTemplateConfigurator, HTMLStencilElement {}
  var HTMLListTemplateConfiguratorElement: {
    prototype: HTMLListTemplateConfiguratorElement;
    new (): HTMLListTemplateConfiguratorElement;
  };
  interface HTMLScxAddModelElement extends Components.ScxAddModel, HTMLStencilElement {}
  var HTMLScxAddModelElement: {
    prototype: HTMLScxAddModelElement;
    new (): HTMLScxAddModelElement;
  };
  interface HTMLScxAddScoreElementEventMap {
    addField: FieldToSend;
    deleteField: number;
    editField: { field: FieldToSend; key: number };
    closeNewDialog: any;
  }
  interface HTMLScxAddScoreElement extends Components.ScxAddScore, HTMLStencilElement {
    addEventListener<K extends keyof HTMLScxAddScoreElementEventMap>(
      type: K,
      listener: (this: HTMLScxAddScoreElement, ev: ScxAddScoreCustomEvent<HTMLScxAddScoreElementEventMap[K]>) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLScxAddScoreElementEventMap>(
      type: K,
      listener: (this: HTMLScxAddScoreElement, ev: ScxAddScoreCustomEvent<HTMLScxAddScoreElementEventMap[K]>) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions
    ): void;
  }
  var HTMLScxAddScoreElement: {
    prototype: HTMLScxAddScoreElement;
    new (): HTMLScxAddScoreElement;
  };
  interface HTMLScxEmptyStateElement extends Components.ScxEmptyState, HTMLStencilElement {}
  var HTMLScxEmptyStateElement: {
    prototype: HTMLScxEmptyStateElement;
    new (): HTMLScxEmptyStateElement;
  };
  /**
   * Example Components Showcase
   * Dynamic tab-based documentation component using Shoelace tabs.
   * Features:
   * - Shoelace sl-tab-group for native tab UI
   * - Easy to add new components (just add to tabs array)
   * - Live interactive examples
   * - Code snippets with syntax highlighting
   * - API documentation tables
   * Adding a new component:
   * 1. Add new object to `tabs` array in componentWillLoad()
   * 2. Create render method for content
   * 3. Done! Tab is automatically rendered
   * Usage:
   * ```html
   * <scx-example-components></scx-example-components>
   * ```
   */
  interface HTMLScxExampleComponentsElement extends Components.ScxExampleComponents, HTMLStencilElement {}
  var HTMLScxExampleComponentsElement: {
    prototype: HTMLScxExampleComponentsElement;
    new (): HTMLScxExampleComponentsElement;
  };
  /**
   * Range Example Component
   * Demonstrates various use cases of the Shoelace sl-range component with different configurations.
   * Features:
   * - Basic range slider with default settings
   * - Custom min, max, and step values
   * - Range with labels and help text
   * - Range with tooltip for real-time value display
   * - Disabled state demonstration
   * - Multiple ranges with different configurations
   * - Real-time value updates
   * Usage:
   * ```html
   * <scx-example-range></scx-example-range>
   * ```
   * sl-range Documentation:
   * https://shoelace.style/components/range
   */
  interface HTMLScxExampleRangeElement extends Components.ScxExampleRange, HTMLStencilElement {}
  var HTMLScxExampleRangeElement: {
    prototype: HTMLScxExampleRangeElement;
    new (): HTMLScxExampleRangeElement;
  };
  interface HTMLScxFileUploaderElementEventMap {
    iconClick: void;
  }
  interface HTMLScxFileUploaderElement extends Components.ScxFileUploader, HTMLStencilElement {
    addEventListener<K extends keyof HTMLScxFileUploaderElementEventMap>(
      type: K,
      listener: (
        this: HTMLScxFileUploaderElement,
        ev: ScxFileUploaderCustomEvent<HTMLScxFileUploaderElementEventMap[K]>
      ) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLScxFileUploaderElementEventMap>(
      type: K,
      listener: (
        this: HTMLScxFileUploaderElement,
        ev: ScxFileUploaderCustomEvent<HTMLScxFileUploaderElementEventMap[K]>
      ) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions
    ): void;
  }
  var HTMLScxFileUploaderElement: {
    prototype: HTMLScxFileUploaderElement;
    new (): HTMLScxFileUploaderElement;
  };
  interface HTMLScxIconsExampleElement extends Components.ScxIconsExample, HTMLStencilElement {}
  var HTMLScxIconsExampleElement: {
    prototype: HTMLScxIconsExampleElement;
    new (): HTMLScxIconsExampleElement;
  };
  interface HTMLScxMappingTableElementEventMap {
    changePage: string;
  }
  interface HTMLScxMappingTableElement extends Components.ScxMappingTable, HTMLStencilElement {
    addEventListener<K extends keyof HTMLScxMappingTableElementEventMap>(
      type: K,
      listener: (
        this: HTMLScxMappingTableElement,
        ev: ScxMappingTableCustomEvent<HTMLScxMappingTableElementEventMap[K]>
      ) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLScxMappingTableElementEventMap>(
      type: K,
      listener: (
        this: HTMLScxMappingTableElement,
        ev: ScxMappingTableCustomEvent<HTMLScxMappingTableElementEventMap[K]>
      ) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions
    ): void;
  }
  var HTMLScxMappingTableElement: {
    prototype: HTMLScxMappingTableElement;
    new (): HTMLScxMappingTableElement;
  };
  /**
   * Example Modal Component
   * Demonstrates how to create a modal content component that works with the Modal Service.
   * Key Patterns:
   * - Receives `modal` prop from Modal Service
   * - Calls `modal.close()` with appropriate data
   * - Uses confirm/dismiss flags to indicate user action
   * - Follows standard modal structure with modal-wrapper, modal-head, modal-content, modal-footer
   * Usage:
   * ```typescript
   * import { starter } from '../../di/containers';
   * const modal = starter.modal;
   * modal.create({
   *   component: 'scx-example-modal',
   *   width: '500px',
   *   dismissOnEsc: true,
   *   backdropDismiss: true,
   *   componentProps: {
   *     modalTitle: 'Confirm Action',
   *     message: 'Are you sure you want to proceed?'
   *   }
   * });
   * modal.onDismiss((data) => {
   *   if (data.confirm) {
   *     console.log('User confirmed');
   *   } else {
   *     console.log('User cancelled');
   *   }
   * });
   * modal.show();
   * ```
   */
  interface HTMLScxModalExampleElement extends Components.ScxModalExample, HTMLStencilElement {}
  var HTMLScxModalExampleElement: {
    prototype: HTMLScxModalExampleElement;
    new (): HTMLScxModalExampleElement;
  };
  interface HTMLScxRadioButtonElementEventMap {
    smStyle: StyleEventDetail;
    smSelect: { checked: boolean; value: unknown };
    smDeselect: void;
    smFocus: void;
    smBlur: void;
  }
  interface HTMLScxRadioButtonElement extends Components.ScxRadioButton, HTMLStencilElement {
    addEventListener<K extends keyof HTMLScxRadioButtonElementEventMap>(
      type: K,
      listener: (
        this: HTMLScxRadioButtonElement,
        ev: ScxRadioButtonCustomEvent<HTMLScxRadioButtonElementEventMap[K]>
      ) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLScxRadioButtonElementEventMap>(
      type: K,
      listener: (
        this: HTMLScxRadioButtonElement,
        ev: ScxRadioButtonCustomEvent<HTMLScxRadioButtonElementEventMap[K]>
      ) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions
    ): void;
  }
  var HTMLScxRadioButtonElement: {
    prototype: HTMLScxRadioButtonElement;
    new (): HTMLScxRadioButtonElement;
  };
  interface HTMLScxRadioGroupElementEventMap {
    smChange: RadioGroupChangeEventDetail;
  }
  interface HTMLScxRadioGroupElement extends Components.ScxRadioGroup, HTMLStencilElement {
    addEventListener<K extends keyof HTMLScxRadioGroupElementEventMap>(
      type: K,
      listener: (
        this: HTMLScxRadioGroupElement,
        ev: ScxRadioGroupCustomEvent<HTMLScxRadioGroupElementEventMap[K]>
      ) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLScxRadioGroupElementEventMap>(
      type: K,
      listener: (
        this: HTMLScxRadioGroupElement,
        ev: ScxRadioGroupCustomEvent<HTMLScxRadioGroupElementEventMap[K]>
      ) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions
    ): void;
  }
  var HTMLScxRadioGroupElement: {
    prototype: HTMLScxRadioGroupElement;
    new (): HTMLScxRadioGroupElement;
  };
  interface HTMLScxRootElement extends Components.ScxRoot, HTMLStencilElement {}
  var HTMLScxRootElement: {
    prototype: HTMLScxRootElement;
    new (): HTMLScxRootElement;
  };
  interface HTMLScxScoreFieldElementEventMap {
    editScore: Score;
    deleteScore: number;
    editCheck: 1 | 3 | null;
  }
  interface HTMLScxScoreFieldElement extends Components.ScxScoreField, HTMLStencilElement {
    addEventListener<K extends keyof HTMLScxScoreFieldElementEventMap>(
      type: K,
      listener: (
        this: HTMLScxScoreFieldElement,
        ev: ScxScoreFieldCustomEvent<HTMLScxScoreFieldElementEventMap[K]>
      ) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLScxScoreFieldElementEventMap>(
      type: K,
      listener: (
        this: HTMLScxScoreFieldElement,
        ev: ScxScoreFieldCustomEvent<HTMLScxScoreFieldElementEventMap[K]>
      ) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions
    ): void;
  }
  var HTMLScxScoreFieldElement: {
    prototype: HTMLScxScoreFieldElement;
    new (): HTMLScxScoreFieldElement;
  };
  interface HTMLScxScorePanelElement extends Components.ScxScorePanel, HTMLStencilElement {}
  var HTMLScxScorePanelElement: {
    prototype: HTMLScxScorePanelElement;
    new (): HTMLScxScorePanelElement;
  };
  /**
   * Tabulator Example Component
   * Demonstrates how to use Tabulator with custom styling and sorting.
   * Features:
   * - Custom theme using tabulator-theme mixin
   * - Sortable columns (click headers)
   * - Movable rows (drag and drop)
   * - Sample data with multiple types
   * - Responsive layout
   * - Pagination
   * Usage:
   * ```html
   * <scx-tabulator-example></scx-tabulator-example>
   * ```
   */
  interface HTMLScxTabulatorExampleElement extends Components.ScxTabulatorExample, HTMLStencilElement {}
  var HTMLScxTabulatorExampleElement: {
    prototype: HTMLScxTabulatorExampleElement;
    new (): HTMLScxTabulatorExampleElement;
  };
  /**
   * Outbound Manager Application Component
   * Demonstrates core patterns for SmileCX applications:
   * - Service access via container getter (NOT
   * @Prop injection)
   * - Reactive state with BehaviorSubject subscriptions
   * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
   * - Event handlers for user interactions
   * - i18n with tt() function
   * This component is the reference implementation for external developers
   * building their own SmileCX-compatible applications.
   * Pattern: Application layer (business logic + UI)
   */
  interface HTMLSmilecxOutboundManagerElement extends Components.SmilecxOutboundManager, HTMLStencilElement {}
  var HTMLSmilecxOutboundManagerElement: {
    prototype: HTMLSmilecxOutboundManagerElement;
    new (): HTMLSmilecxOutboundManagerElement;
  };
  interface HTMLElementTagNameMap {
    'list-template-configurator': HTMLListTemplateConfiguratorElement;
    'scx-add-model': HTMLScxAddModelElement;
    'scx-add-score': HTMLScxAddScoreElement;
    'scx-empty-state': HTMLScxEmptyStateElement;
    'scx-example-components': HTMLScxExampleComponentsElement;
    'scx-example-range': HTMLScxExampleRangeElement;
    'scx-file-uploader': HTMLScxFileUploaderElement;
    'scx-icons-example': HTMLScxIconsExampleElement;
    'scx-mapping-table': HTMLScxMappingTableElement;
    'scx-modal-example': HTMLScxModalExampleElement;
    'scx-radio-button': HTMLScxRadioButtonElement;
    'scx-radio-group': HTMLScxRadioGroupElement;
    'scx-root': HTMLScxRootElement;
    'scx-score-field': HTMLScxScoreFieldElement;
    'scx-score-panel': HTMLScxScorePanelElement;
    'scx-tabulator-example': HTMLScxTabulatorExampleElement;
    'smilecx-outbound-manager': HTMLSmilecxOutboundManagerElement;
  }
}
declare namespace LocalJSX {
  type OneOf<K extends string, PropT, AttrT = PropT> =
    | ({ [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never })
    | ({ [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never })
    | ({ [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never });

  interface ListTemplateConfigurator {
    modal: IModal;
  }
  interface ScxAddModel {}
  interface ScxAddScore {
    addNewField?: boolean;
    /**
     * @default { ...this.initField }
     */
    field?: FieldToSend;
    /**
     * @default 0
     */
    fieldIndex?: number;
    onAddField?: (event: ScxAddScoreCustomEvent<FieldToSend>) => void;
    onCloseNewDialog?: (event: ScxAddScoreCustomEvent<any>) => void;
    onDeleteField?: (event: ScxAddScoreCustomEvent<number>) => void;
    onEditField?: (event: ScxAddScoreCustomEvent<{ field: FieldToSend; key: number }>) => void;
    scope: 'Contactability' | 'Propensity';
  }
  interface ScxEmptyState {
    esTitle?: string;
    icon: string;
    label?: string;
  }
  /**
   * Example Components Showcase
   * Dynamic tab-based documentation component using Shoelace tabs.
   * Features:
   * - Shoelace sl-tab-group for native tab UI
   * - Easy to add new components (just add to tabs array)
   * - Live interactive examples
   * - Code snippets with syntax highlighting
   * - API documentation tables
   * Adding a new component:
   * 1. Add new object to `tabs` array in componentWillLoad()
   * 2. Create render method for content
   * 3. Done! Tab is automatically rendered
   * Usage:
   * ```html
   * <scx-example-components></scx-example-components>
   * ```
   */
  interface ScxExampleComponents {}
  /**
   * Range Example Component
   * Demonstrates various use cases of the Shoelace sl-range component with different configurations.
   * Features:
   * - Basic range slider with default settings
   * - Custom min, max, and step values
   * - Range with labels and help text
   * - Range with tooltip for real-time value display
   * - Disabled state demonstration
   * - Multiple ranges with different configurations
   * - Real-time value updates
   * Usage:
   * ```html
   * <scx-example-range></scx-example-range>
   * ```
   * sl-range Documentation:
   * https://shoelace.style/components/range
   */
  interface ScxExampleRange {}
  interface ScxFileUploader {
    esTitle?: string;
    icon: string;
    label?: string;
    onIconClick?: (event: ScxFileUploaderCustomEvent<void>) => void;
  }
  interface ScxIconsExample {}
  interface ScxMappingTable {
    onChangePage?: (event: ScxMappingTableCustomEvent<string>) => void;
  }
  /**
   * Example Modal Component
   * Demonstrates how to create a modal content component that works with the Modal Service.
   * Key Patterns:
   * - Receives `modal` prop from Modal Service
   * - Calls `modal.close()` with appropriate data
   * - Uses confirm/dismiss flags to indicate user action
   * - Follows standard modal structure with modal-wrapper, modal-head, modal-content, modal-footer
   * Usage:
   * ```typescript
   * import { starter } from '../../di/containers';
   * const modal = starter.modal;
   * modal.create({
   *   component: 'scx-example-modal',
   *   width: '500px',
   *   dismissOnEsc: true,
   *   backdropDismiss: true,
   *   componentProps: {
   *     modalTitle: 'Confirm Action',
   *     message: 'Are you sure you want to proceed?'
   *   }
   * });
   * modal.onDismiss((data) => {
   *   if (data.confirm) {
   *     console.log('User confirmed');
   *   } else {
   *     console.log('User cancelled');
   *   }
   * });
   * modal.show();
   * ```
   */
  interface ScxModalExample {
    /**
     * Modal message (optional) Passed via componentProps
     * @default 'This is an example modal component.'
     */
    message?: string;
    /**
     * Modal service reference Automatically injected by Modal Service
     */
    modal: IModal;
    /**
     * Modal title (optional) Passed via componentProps
     * @default 'Example Modal'
     */
    modalTitle?: string;
  }
  interface ScxRadioButton {
    /**
     * If `true`, the radio is selected.
     * @default false
     */
    checked?: boolean;
    /**
     * If `true`, the user cannot interact with the radio.
     * @default false
     */
    disabled?: boolean;
    /**
     * The name of the control, which is submitted with the form data.
     * @default this.inputId
     */
    name?: string;
    /**
     * Emitted when the radio button loses focus.
     */
    onSmBlur?: (event: ScxRadioButtonCustomEvent<void>) => void;
    /**
     * Emitted when a checked radio button is deselected.
     */
    onSmDeselect?: (event: ScxRadioButtonCustomEvent<void>) => void;
    /**
     * Emitted when the radio button gains focus.
     */
    onSmFocus?: (event: ScxRadioButtonCustomEvent<void>) => void;
    /**
     * Emitted when the radio button is selected.
     */
    onSmSelect?: (event: ScxRadioButtonCustomEvent<{ checked: boolean; value: unknown }>) => void;
    /**
     * Emitted when the styles change.
     */
    onSmStyle?: (event: ScxRadioButtonCustomEvent<StyleEventDetail>) => void;
    /**
     * The size of the radio button.
     * @default 'medium'
     */
    size?: 'small' | 'medium' | 'large';
    /**
     * The value of the radio button.
     */
    value?: unknown;
    /**
     * The color variant of the radio button.
     * @default 'default'
     */
    variant?: 'default' | 'neutral' | 'light';
  }
  interface ScxRadioGroup {
    /**
     * If `true`, the radios can be deselected.
     * @default false
     */
    allowEmptySelection?: boolean;
    /**
     * The size variant of the radio group. With hug each button accords its size to its content.
     * @default 'fill'
     */
    contain?: 'fill' | 'hug';
    /**
     * The name of the control, which is submitted with the form data.
     * @default this.inputId
     */
    name?: string;
    /**
     * Emitted when the value has changed.
     */
    onSmChange?: (event: ScxRadioGroupCustomEvent<RadioGroupChangeEventDetail>) => void;
    /**
     * The size of the radio buttons.
     * @default 'medium'
     */
    size?: 'small' | 'medium' | 'large';
    /**
     * The value of the radio group.
     */
    value?: unknown | null;
    /**
     * The color variant of the radio group.
     * @default 'default'
     */
    variant?: 'default' | 'neutral' | 'light';
  }
  interface ScxRoot {
    /**
     * @default ''
     */
    apiUrl?: string;
  }
  interface ScxScoreField {
    editMode: boolean;
    field: FieldToSend;
    nScore: number;
    onDeleteScore?: (event: ScxScoreFieldCustomEvent<number>) => void;
    onEditCheck?: (event: ScxScoreFieldCustomEvent<1 | 3 | null>) => void;
    onEditScore?: (event: ScxScoreFieldCustomEvent<Score>) => void;
    /**
     * @default []
     */
    otherScore?: Score[];
    switch?: 1 | 3 | null;
  }
  interface ScxScorePanel {
    scope: 'Contactability' | 'Propensity';
  }
  /**
   * Tabulator Example Component
   * Demonstrates how to use Tabulator with custom styling and sorting.
   * Features:
   * - Custom theme using tabulator-theme mixin
   * - Sortable columns (click headers)
   * - Movable rows (drag and drop)
   * - Sample data with multiple types
   * - Responsive layout
   * - Pagination
   * Usage:
   * ```html
   * <scx-tabulator-example></scx-tabulator-example>
   * ```
   */
  interface ScxTabulatorExample {}
  /**
   * Outbound Manager Application Component
   * Demonstrates core patterns for SmileCX applications:
   * - Service access via container getter (NOT
   * @Prop injection)
   * - Reactive state with BehaviorSubject subscriptions
   * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
   * - Event handlers for user interactions
   * - i18n with tt() function
   * This component is the reference implementation for external developers
   * building their own SmileCX-compatible applications.
   * Pattern: Application layer (business logic + UI)
   */
  interface SmilecxOutboundManager {}

  interface ScxAddScoreAttributes {
    addNewField: boolean;
    fieldIndex: number;
    scope: 'Contactability' | 'Propensity';
  }
  interface ScxEmptyStateAttributes {
    icon: string;
    label: string;
    esTitle: string;
  }
  interface ScxFileUploaderAttributes {
    icon: string;
    label: string;
    esTitle: string;
  }
  interface ScxModalExampleAttributes {
    modalTitle: string;
    message: string;
  }
  interface ScxRadioButtonAttributes {
    name: string;
    disabled: boolean;
    checked: boolean;
    variant: 'default' | 'neutral' | 'light';
    size: 'small' | 'medium' | 'large';
  }
  interface ScxRadioGroupAttributes {
    allowEmptySelection: boolean;
    name: string;
    size: 'small' | 'medium' | 'large';
    contain: 'fill' | 'hug';
    variant: 'default' | 'neutral' | 'light';
  }
  interface ScxRootAttributes {
    apiUrl: string;
  }
  interface ScxScoreFieldAttributes {
    editMode: boolean;
    nScore: number;
    switch: 1 | 3 | null;
  }
  interface ScxScorePanelAttributes {
    scope: 'Contactability' | 'Propensity';
  }

  interface IntrinsicElements {
    'list-template-configurator': ListTemplateConfigurator;
    'scx-add-model': ScxAddModel;
    'scx-add-score': Omit<ScxAddScore, keyof ScxAddScoreAttributes> & {
      [K in keyof ScxAddScore & keyof ScxAddScoreAttributes]?: ScxAddScore[K];
    } & { [K in keyof ScxAddScore & keyof ScxAddScoreAttributes as `attr:${K}`]?: ScxAddScoreAttributes[K] } & {
      [K in keyof ScxAddScore & keyof ScxAddScoreAttributes as `prop:${K}`]?: ScxAddScore[K];
    } & OneOf<'scope', ScxAddScore['scope'], ScxAddScoreAttributes['scope']>;
    'scx-empty-state': Omit<ScxEmptyState, keyof ScxEmptyStateAttributes> & {
      [K in keyof ScxEmptyState & keyof ScxEmptyStateAttributes]?: ScxEmptyState[K];
    } & { [K in keyof ScxEmptyState & keyof ScxEmptyStateAttributes as `attr:${K}`]?: ScxEmptyStateAttributes[K] } & {
      [K in keyof ScxEmptyState & keyof ScxEmptyStateAttributes as `prop:${K}`]?: ScxEmptyState[K];
    } & OneOf<'icon', ScxEmptyState['icon'], ScxEmptyStateAttributes['icon']>;
    'scx-example-components': ScxExampleComponents;
    'scx-example-range': ScxExampleRange;
    'scx-file-uploader': Omit<ScxFileUploader, keyof ScxFileUploaderAttributes> & {
      [K in keyof ScxFileUploader & keyof ScxFileUploaderAttributes]?: ScxFileUploader[K];
    } & {
      [K in keyof ScxFileUploader & keyof ScxFileUploaderAttributes as `attr:${K}`]?: ScxFileUploaderAttributes[K];
    } & { [K in keyof ScxFileUploader & keyof ScxFileUploaderAttributes as `prop:${K}`]?: ScxFileUploader[K] } & OneOf<
        'icon',
        ScxFileUploader['icon'],
        ScxFileUploaderAttributes['icon']
      >;
    'scx-icons-example': ScxIconsExample;
    'scx-mapping-table': ScxMappingTable;
    'scx-modal-example': Omit<ScxModalExample, keyof ScxModalExampleAttributes> & {
      [K in keyof ScxModalExample & keyof ScxModalExampleAttributes]?: ScxModalExample[K];
    } & {
      [K in keyof ScxModalExample & keyof ScxModalExampleAttributes as `attr:${K}`]?: ScxModalExampleAttributes[K];
    } & { [K in keyof ScxModalExample & keyof ScxModalExampleAttributes as `prop:${K}`]?: ScxModalExample[K] };
    'scx-radio-button': Omit<ScxRadioButton, keyof ScxRadioButtonAttributes> & {
      [K in keyof ScxRadioButton & keyof ScxRadioButtonAttributes]?: ScxRadioButton[K];
    } & {
      [K in keyof ScxRadioButton & keyof ScxRadioButtonAttributes as `attr:${K}`]?: ScxRadioButtonAttributes[K];
    } & { [K in keyof ScxRadioButton & keyof ScxRadioButtonAttributes as `prop:${K}`]?: ScxRadioButton[K] };
    'scx-radio-group': Omit<ScxRadioGroup, keyof ScxRadioGroupAttributes> & {
      [K in keyof ScxRadioGroup & keyof ScxRadioGroupAttributes]?: ScxRadioGroup[K];
    } & { [K in keyof ScxRadioGroup & keyof ScxRadioGroupAttributes as `attr:${K}`]?: ScxRadioGroupAttributes[K] } & {
      [K in keyof ScxRadioGroup & keyof ScxRadioGroupAttributes as `prop:${K}`]?: ScxRadioGroup[K];
    };
    'scx-root': Omit<ScxRoot, keyof ScxRootAttributes> & {
      [K in keyof ScxRoot & keyof ScxRootAttributes]?: ScxRoot[K];
    } & { [K in keyof ScxRoot & keyof ScxRootAttributes as `attr:${K}`]?: ScxRootAttributes[K] } & {
      [K in keyof ScxRoot & keyof ScxRootAttributes as `prop:${K}`]?: ScxRoot[K];
    };
    'scx-score-field': Omit<ScxScoreField, keyof ScxScoreFieldAttributes> & {
      [K in keyof ScxScoreField & keyof ScxScoreFieldAttributes]?: ScxScoreField[K];
    } & { [K in keyof ScxScoreField & keyof ScxScoreFieldAttributes as `attr:${K}`]?: ScxScoreFieldAttributes[K] } & {
      [K in keyof ScxScoreField & keyof ScxScoreFieldAttributes as `prop:${K}`]?: ScxScoreField[K];
    } & OneOf<'editMode', ScxScoreField['editMode'], ScxScoreFieldAttributes['editMode']> &
      OneOf<'nScore', ScxScoreField['nScore'], ScxScoreFieldAttributes['nScore']>;
    'scx-score-panel': Omit<ScxScorePanel, keyof ScxScorePanelAttributes> & {
      [K in keyof ScxScorePanel & keyof ScxScorePanelAttributes]?: ScxScorePanel[K];
    } & { [K in keyof ScxScorePanel & keyof ScxScorePanelAttributes as `attr:${K}`]?: ScxScorePanelAttributes[K] } & {
      [K in keyof ScxScorePanel & keyof ScxScorePanelAttributes as `prop:${K}`]?: ScxScorePanel[K];
    } & OneOf<'scope', ScxScorePanel['scope'], ScxScorePanelAttributes['scope']>;
    'scx-tabulator-example': ScxTabulatorExample;
    'smilecx-outbound-manager': SmilecxOutboundManager;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'list-template-configurator': LocalJSX.IntrinsicElements['list-template-configurator'] &
        JSXBase.HTMLAttributes<HTMLListTemplateConfiguratorElement>;
      'scx-add-model': LocalJSX.IntrinsicElements['scx-add-model'] & JSXBase.HTMLAttributes<HTMLScxAddModelElement>;
      'scx-add-score': LocalJSX.IntrinsicElements['scx-add-score'] & JSXBase.HTMLAttributes<HTMLScxAddScoreElement>;
      'scx-empty-state': LocalJSX.IntrinsicElements['scx-empty-state'] &
        JSXBase.HTMLAttributes<HTMLScxEmptyStateElement>;
      /**
       * Example Components Showcase
       * Dynamic tab-based documentation component using Shoelace tabs.
       * Features:
       * - Shoelace sl-tab-group for native tab UI
       * - Easy to add new components (just add to tabs array)
       * - Live interactive examples
       * - Code snippets with syntax highlighting
       * - API documentation tables
       * Adding a new component:
       * 1. Add new object to `tabs` array in componentWillLoad()
       * 2. Create render method for content
       * 3. Done! Tab is automatically rendered
       * Usage:
       * ```html
       * <scx-example-components></scx-example-components>
       * ```
       */
      'scx-example-components': LocalJSX.IntrinsicElements['scx-example-components'] &
        JSXBase.HTMLAttributes<HTMLScxExampleComponentsElement>;
      /**
       * Range Example Component
       * Demonstrates various use cases of the Shoelace sl-range component with different configurations.
       * Features:
       * - Basic range slider with default settings
       * - Custom min, max, and step values
       * - Range with labels and help text
       * - Range with tooltip for real-time value display
       * - Disabled state demonstration
       * - Multiple ranges with different configurations
       * - Real-time value updates
       * Usage:
       * ```html
       * <scx-example-range></scx-example-range>
       * ```
       * sl-range Documentation:
       * https://shoelace.style/components/range
       */
      'scx-example-range': LocalJSX.IntrinsicElements['scx-example-range'] &
        JSXBase.HTMLAttributes<HTMLScxExampleRangeElement>;
      'scx-file-uploader': LocalJSX.IntrinsicElements['scx-file-uploader'] &
        JSXBase.HTMLAttributes<HTMLScxFileUploaderElement>;
      'scx-icons-example': LocalJSX.IntrinsicElements['scx-icons-example'] &
        JSXBase.HTMLAttributes<HTMLScxIconsExampleElement>;
      'scx-mapping-table': LocalJSX.IntrinsicElements['scx-mapping-table'] &
        JSXBase.HTMLAttributes<HTMLScxMappingTableElement>;
      /**
       * Example Modal Component
       * Demonstrates how to create a modal content component that works with the Modal Service.
       * Key Patterns:
       * - Receives `modal` prop from Modal Service
       * - Calls `modal.close()` with appropriate data
       * - Uses confirm/dismiss flags to indicate user action
       * - Follows standard modal structure with modal-wrapper, modal-head, modal-content, modal-footer
       * Usage:
       * ```typescript
       * import { starter } from '../../di/containers';
       * const modal = starter.modal;
       * modal.create({
       *   component: 'scx-example-modal',
       *   width: '500px',
       *   dismissOnEsc: true,
       *   backdropDismiss: true,
       *   componentProps: {
       *     modalTitle: 'Confirm Action',
       *     message: 'Are you sure you want to proceed?'
       *   }
       * });
       * modal.onDismiss((data) => {
       *   if (data.confirm) {
       *     console.log('User confirmed');
       *   } else {
       *     console.log('User cancelled');
       *   }
       * });
       * modal.show();
       * ```
       */
      'scx-modal-example': LocalJSX.IntrinsicElements['scx-modal-example'] &
        JSXBase.HTMLAttributes<HTMLScxModalExampleElement>;
      'scx-radio-button': LocalJSX.IntrinsicElements['scx-radio-button'] &
        JSXBase.HTMLAttributes<HTMLScxRadioButtonElement>;
      'scx-radio-group': LocalJSX.IntrinsicElements['scx-radio-group'] &
        JSXBase.HTMLAttributes<HTMLScxRadioGroupElement>;
      'scx-root': LocalJSX.IntrinsicElements['scx-root'] & JSXBase.HTMLAttributes<HTMLScxRootElement>;
      'scx-score-field': LocalJSX.IntrinsicElements['scx-score-field'] &
        JSXBase.HTMLAttributes<HTMLScxScoreFieldElement>;
      'scx-score-panel': LocalJSX.IntrinsicElements['scx-score-panel'] &
        JSXBase.HTMLAttributes<HTMLScxScorePanelElement>;
      /**
       * Tabulator Example Component
       * Demonstrates how to use Tabulator with custom styling and sorting.
       * Features:
       * - Custom theme using tabulator-theme mixin
       * - Sortable columns (click headers)
       * - Movable rows (drag and drop)
       * - Sample data with multiple types
       * - Responsive layout
       * - Pagination
       * Usage:
       * ```html
       * <scx-tabulator-example></scx-tabulator-example>
       * ```
       */
      'scx-tabulator-example': LocalJSX.IntrinsicElements['scx-tabulator-example'] &
        JSXBase.HTMLAttributes<HTMLScxTabulatorExampleElement>;
      /**
       * Outbound Manager Application Component
       * Demonstrates core patterns for SmileCX applications:
       * - Service access via container getter (NOT
       * @Prop injection)
       * - Reactive state with BehaviorSubject subscriptions
       * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
       * - Event handlers for user interactions
       * - i18n with tt() function
       * This component is the reference implementation for external developers
       * building their own SmileCX-compatible applications.
       * Pattern: Application layer (business logic + UI)
       */
      'smilecx-outbound-manager': LocalJSX.IntrinsicElements['smilecx-outbound-manager'] &
        JSXBase.HTMLAttributes<HTMLSmilecxOutboundManagerElement>;
    }
  }
}
